"""add initiative fields to token

Revision ID: be692d28ef14
Revises: bc85dc94a320
Create Date: 2026-08-06 04:10:17.834745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be692d28ef14'
down_revision: Union[str, Sequence[str], None] = 'bc85dc94a320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен только чтобы забэкфилить уже существующие строки
    # (у модели default= — это application-side default для новых инсертов,
    # он не помогает ALTER TABLE ... NOT NULL на непустой таблице); дальше
    # убираем его, чтобы дефолт управлялся только на стороне приложения.
    op.add_column('tokens', sa.Column('in_initiative', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tokens', sa.Column('initiative_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tokens', sa.Column('initiative_stats_visible_to_players', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('tokens', 'in_initiative', server_default=None)
    op.alter_column('tokens', 'initiative_order', server_default=None)
    op.alter_column('tokens', 'initiative_stats_visible_to_players', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'initiative_stats_visible_to_players')
    op.drop_column('tokens', 'initiative_order')
    op.drop_column('tokens', 'in_initiative')
    # ### end Alembic commands ###
